import { Company, Employee, AttendanceRecord, TimeOffRequest, TimeOffAllocation } from './types';
import { createDefaultSalaryStructure } from './utils/salaryCalculator';

export const initialCompany: Company = {
  name: 'Odoo India',
  code: 'OI',
  logoUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=160&auto=format&fit=crop&q=80',
  email: 'hr@odooindia.com',
  phone: '+91 79 4000 8000',
  address: 'Infocity Tower 2, Gandhinagar, Gujarat 382007',
};

export const initialEmployees: Employee[] = [
  {
    id: 'emp-1',
    loginId: 'OIAMSH20210001',
    firstName: 'Amit',
    lastName: 'Sharma',
    fullName: 'Amit Sharma',
    email: 'amit.sharma@odooindia.com',
    personalEmail: 'amit.sharma.personal@gmail.com',
    mobile: '+91 98250 11223',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&auto=format&fit=crop&q=80',
    company: 'Odoo India',
    department: 'Human Resources',
    manager: 'Director of People Ops',
    location: 'Gandhinagar Hub',
    jobPosition: 'Head HR Officer / Admin',
    role: 'admin',
    dateOfJoining: '2021-04-15',
    joiningYear: 2021,
    serialNumber: 1,
    status: 'present',
    about: 'Strategic HR leader with 8+ years of experience leading talent acquisition, organization design, employee engagement, and compensation planning in fast-growing tech enterprises.',
    skills: ['Talent Strategy', 'People Analytics', 'Compensation & Benefits', 'Conflict Resolution', 'HR Policy & Compliance', 'Leadership'],
    certifications: ['SHRM Senior Certified Professional (SHRM-SCP)', 'Certified Compensation Professional (CCP)', 'Advanced People Analytics'],
    whatILoveAboutJob: 'Fostering an inclusive and vibrant workplace culture where top engineering and design talents thrive and do their best work.',
    interestsAndHobbies: 'Classical chess, marathon running, hiking in the Sahyadris, and reading behavioral economics.',
    residingAddress: 'Flat 402, Green Acre Heights, Bodakdev, Ahmedabad, Gujarat 380054',
    dateOfBirth: '1989-08-14',
    nationality: 'Indian',
    gender: 'Male',
    maritalStatus: 'Married',
    empCode: 'OI-HR-001',
    bankDetails: {
      accountNumber: '918273645019',
      bankName: 'HDFC Bank',
      ifscCode: 'HDFC0001245',
      uanNumber: '100892019482',
      panNumber: 'ABCPS1289K',
    },
    passwordHash: 'password123',
    salary: createDefaultSalaryStructure(95000),
  },
  {
    id: 'emp-2',
    loginId: 'OIJODO20220002',
    firstName: 'John',
    lastName: 'Doe',
    fullName: 'John Doe',
    email: 'john.doe@odooindia.com',
    personalEmail: 'johndoe.dev@gmail.com',
    mobile: '+91 98980 44556',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&auto=format&fit=crop&q=80',
    company: 'Odoo India',
    department: 'Frontend Engineering',
    manager: 'Amit Sharma',
    location: 'Gandhinagar Hub',
    jobPosition: 'Senior Frontend Engineer',
    role: 'employee',
    dateOfJoining: '2022-06-01',
    joiningYear: 2022,
    serialNumber: 2,
    status: 'present',
    about: 'Passionate UI/UX and Frontend Architect dedicated to building delightful, lightning-fast web applications with modern React, TypeScript, and micro-frontends.',
    skills: ['React 19', 'TypeScript', 'Tailwind CSS', 'Vite', 'State Management', 'Web Performance Optimization', 'Design Systems'],
    certifications: ['AWS Certified Cloud Practitioner', 'Meta Frontend Developer Specialization', 'Google Mobile Web Specialist'],
    whatILoveAboutJob: 'Turning complex business operations into intuitive, friction-free visual workflows that thousands of teams rely on every single day.',
    interestsAndHobbies: 'Mechanical keyboards tinkering, specialty coffee brewing, and open-source contributions.',
    residingAddress: 'B-704, Shivalik Residency, Kudasan, Gandhinagar 382421',
    dateOfBirth: '1994-03-22',
    nationality: 'Indian',
    gender: 'Male',
    maritalStatus: 'Single',
    empCode: 'OI-ENG-002',
    bankDetails: {
      accountNumber: '449102948192',
      bankName: 'ICICI Bank',
      ifscCode: 'ICIC0000342',
      uanNumber: '100918274619',
      panNumber: 'BKOPD4910L',
    },
    passwordHash: 'password123',
    salary: createDefaultSalaryStructure(75000),
  },
  {
    id: 'emp-3',
    loginId: 'OIPRPA20230003',
    firstName: 'Priya',
    lastName: 'Patel',
    fullName: 'Priya Patel',
    email: 'priya.patel@odooindia.com',
    personalEmail: 'priya.designs@gmail.com',
    mobile: '+91 97123 55667',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=200&auto=format&fit=crop&q=80',
    company: 'Odoo India',
    department: 'Product Design',
    manager: 'Sneha Kulkarni',
    location: 'Gandhinagar Hub',
    jobPosition: 'Lead UI/UX Designer',
    role: 'employee',
    dateOfJoining: '2023-01-10',
    joiningYear: 2023,
    serialNumber: 3,
    status: 'on_leave',
    about: 'Design systems fanatic crafting high-density enterprise software experiences with clarity, empathetic ergonomics, and accessible aesthetics.',
    skills: ['Figma Master', 'Design Systems', 'User Research', 'Information Architecture', 'Prototyping', 'Accessibility (WCAG)'],
    certifications: ['Nielsen Norman Group UX Master Certified', 'Interaction Design Foundation (IxDF) Specialist'],
    whatILoveAboutJob: 'Solving deep systemic workflow problems and observing our users navigate tools with zero cognitive friction.',
    interestsAndHobbies: 'Watercolor landscape illustration, ceramic pottery, and architectural photography.',
    residingAddress: '12, Shanti Niketan Society, Satellite Road, Ahmedabad 380015',
    dateOfBirth: '1995-11-05',
    nationality: 'Indian',
    gender: 'Female',
    maritalStatus: 'Single',
    empCode: 'OI-DES-003',
    bankDetails: {
      accountNumber: '338192019481',
      bankName: 'State Bank of India',
      ifscCode: 'SBIN0004120',
      uanNumber: '100481920194',
      panNumber: 'CRXPP8291M',
    },
    passwordHash: 'password123',
    salary: createDefaultSalaryStructure(70000),
  },
  {
    id: 'emp-4',
    loginId: 'OIRAVE20220004',
    firstName: 'Rahul',
    lastName: 'Verma',
    fullName: 'Rahul Verma',
    email: 'rahul.verma@odooindia.com',
    personalEmail: 'rahul.verma.backend@gmail.com',
    mobile: '+91 94280 88990',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&auto=format&fit=crop&q=80',
    company: 'Odoo India',
    department: 'Platform & Cloud Infrastructure',
    manager: 'Amit Sharma',
    location: 'Gandhinagar Hub',
    jobPosition: 'Principal Backend Architect',
    role: 'employee',
    dateOfJoining: '2022-09-15',
    joiningYear: 2022,
    serialNumber: 4,
    status: 'absent',
    about: 'Distributed systems engineer with deep expertise in high-throughput transactional databases, microservices mesh, and cloud-native resilience.',
    skills: ['Node.js', 'Go', 'PostgreSQL', 'Redis', 'Kubernetes', 'Distributed Systems', 'gRPC'],
    certifications: ['Certified Kubernetes Administrator (CKA)', 'Google Cloud Certified Professional Cloud Architect'],
    whatILoveAboutJob: 'Building distributed infrastructure that smoothly handles millions of background tasks with sub-millisecond latency.',
    interestsAndHobbies: 'Home automation IoT setups, synthesizer music, and sci-fi literature.',
    residingAddress: 'Flat 503, Galaxy Heights, Infocity Cross Road, Gandhinagar 382009',
    dateOfBirth: '1991-05-18',
    nationality: 'Indian',
    gender: 'Male',
    maritalStatus: 'Married',
    empCode: 'OI-ENG-004',
    bankDetails: {
      accountNumber: '881920391029',
      bankName: 'Axis Bank',
      ifscCode: 'UTIB0001092',
      uanNumber: '100918471029',
      panNumber: 'ALMPV9012R',
    },
    passwordHash: 'password123',
    salary: createDefaultSalaryStructure(85000),
  },
  {
    id: 'emp-5',
    loginId: 'OISNKU20240005',
    firstName: 'Sneha',
    lastName: 'Kulkarni',
    fullName: 'Sneha Kulkarni',
    email: 'sneha.kulkarni@odooindia.com',
    personalEmail: 'sneha.k@outlook.com',
    mobile: '+91 99090 12345',
    avatarUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=200&auto=format&fit=crop&q=80',
    company: 'Odoo India',
    department: 'Product Management',
    manager: 'Amit Sharma',
    location: 'Gandhinagar Hub',
    jobPosition: 'Senior Product Manager',
    role: 'employee',
    dateOfJoining: '2024-02-01',
    joiningYear: 2024,
    serialNumber: 5,
    status: 'present',
    about: 'Data-driven Product Leader bridging customer discovery, engineering velocity, and business growth to build high-impact enterprise SaaS products.',
    skills: ['Product Discovery', 'Roadmap Prioritization', 'Data Analytics', 'Agile & Scrum', 'User Interviews', 'Go-To-Market'],
    certifications: ['Pragmatic Institute Certified (PMC-III)', 'Certified Scrum Product Owner (CSPO)'],
    whatILoveAboutJob: 'Empowering cross-functional teams to launch high-leverage products that delight end-users.',
    interestsAndHobbies: 'Badminton, baking artisanal sourdough, and podcasting on tech culture.',
    residingAddress: 'A-201, Maple Tree Garden Homes, Near Surdhara Circle, Thaltej, Ahmedabad 380059',
    dateOfBirth: '1993-07-30',
    nationality: 'Indian',
    gender: 'Female',
    maritalStatus: 'Married',
    empCode: 'OI-PM-005',
    bankDetails: {
      accountNumber: '551029481920',
      bankName: 'HDFC Bank',
      ifscCode: 'HDFC0000049',
      uanNumber: '100719204910',
      panNumber: 'BNMKS7102P',
    },
    passwordHash: 'password123',
    salary: createDefaultSalaryStructure(80000),
  },
  {
    id: 'emp-6',
    loginId: 'OIVIMA20230006',
    firstName: 'Vikram',
    lastName: 'Malhotra',
    fullName: 'Vikram Malhotra',
    email: 'vikram.m@odooindia.com',
    personalEmail: 'vikram.malhotra.qa@gmail.com',
    mobile: '+91 98765 43210',
    avatarUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=200&auto=format&fit=crop&q=80',
    company: 'Odoo India',
    department: 'Quality Assurance',
    manager: 'John Doe',
    location: 'Gandhinagar Hub',
    jobPosition: 'QA Automation Lead',
    role: 'employee',
    dateOfJoining: '2023-08-15',
    joiningYear: 2023,
    serialNumber: 6,
    status: 'present',
    about: 'Quality engineer championing automated testing frameworks, CI/CD pipeline test gates, and continuous performance telemetry.',
    skills: ['Playwright', 'Cypress', 'Selenium', 'Load Testing', 'CI/CD Pipelines', 'API Testing (Postman/Newman)'],
    certifications: ['ISTQB Advanced Level Test Automation Engineer', 'AWS DevOps Certified'],
    whatILoveAboutJob: 'Ensuring absolute reliability and peace of mind with every deployment to production.',
    interestsAndHobbies: 'Guitar, vinyl record collecting, and board game strategy nights.',
    residingAddress: 'Flat 101, Nilkanth Elegance, Raysan, Gandhinagar 382426',
    dateOfBirth: '1992-12-10',
    nationality: 'Indian',
    gender: 'Male',
    maritalStatus: 'Single',
    empCode: 'OI-QA-006',
    bankDetails: {
      accountNumber: '661920491029',
      bankName: 'Kotak Mahindra Bank',
      ifscCode: 'KKBK0000812',
      uanNumber: '100619284019',
      panNumber: 'CZXPM6192Q',
    },
    passwordHash: 'password123',
    salary: createDefaultSalaryStructure(65000),
  },
];

export const initialAttendanceRecords: AttendanceRecord[] = [
  // 22 October 2025
  {
    id: 'att-1',
    employeeId: 'emp-1',
    employeeName: 'Amit Sharma',
    employeeAvatar: initialEmployees[0].avatarUrl,
    date: '2025-10-22',
    checkIn: '09:15 AM',
    checkOut: '06:15 PM',
    workHours: 8.0,
    breakMinutes: 60,
    extraHours: 0.0,
    status: 'present',
  },
  {
    id: 'att-2',
    employeeId: 'emp-2',
    employeeName: 'John Doe',
    employeeAvatar: initialEmployees[1].avatarUrl,
    date: '2025-10-22',
    checkIn: '09:30 AM',
    checkOut: '07:00 PM',
    workHours: 8.5,
    breakMinutes: 60,
    extraHours: 0.5,
    status: 'present',
  },
  {
    id: 'att-3',
    employeeId: 'emp-3',
    employeeName: 'Priya Patel',
    employeeAvatar: initialEmployees[2].avatarUrl,
    date: '2025-10-22',
    checkIn: '-',
    checkOut: '-',
    workHours: 0.0,
    breakMinutes: 0,
    extraHours: 0.0,
    status: 'on_leave',
    notes: 'Approved Paid Time Off',
  },
  {
    id: 'att-4',
    employeeId: 'emp-4',
    employeeName: 'Rahul Verma',
    employeeAvatar: initialEmployees[3].avatarUrl,
    date: '2025-10-22',
    checkIn: '-',
    checkOut: '-',
    workHours: 0.0,
    breakMinutes: 0,
    extraHours: 0.0,
    status: 'absent',
    notes: 'Unexcused / Missing punch',
  },
  {
    id: 'att-5',
    employeeId: 'emp-5',
    employeeName: 'Sneha Kulkarni',
    employeeAvatar: initialEmployees[4].avatarUrl,
    date: '2025-10-22',
    checkIn: '09:05 AM',
    checkOut: '06:35 PM',
    workHours: 8.5,
    breakMinutes: 60,
    extraHours: 0.5,
    status: 'present',
  },
  {
    id: 'att-6',
    employeeId: 'emp-6',
    employeeName: 'Vikram Malhotra',
    employeeAvatar: initialEmployees[5].avatarUrl,
    date: '2025-10-22',
    checkIn: '09:45 AM',
    checkOut: '06:45 PM',
    workHours: 8.0,
    breakMinutes: 60,
    extraHours: 0.0,
    status: 'present',
  },

  // 21 October 2025
  {
    id: 'att-7',
    employeeId: 'emp-1',
    employeeName: 'Amit Sharma',
    employeeAvatar: initialEmployees[0].avatarUrl,
    date: '2025-10-21',
    checkIn: '09:00 AM',
    checkOut: '06:00 PM',
    workHours: 8.0,
    breakMinutes: 60,
    extraHours: 0.0,
    status: 'present',
  },
  {
    id: 'att-8',
    employeeId: 'emp-2',
    employeeName: 'John Doe',
    employeeAvatar: initialEmployees[1].avatarUrl,
    date: '2025-10-21',
    checkIn: '09:15 AM',
    checkOut: '06:45 PM',
    workHours: 8.5,
    breakMinutes: 60,
    extraHours: 0.5,
    status: 'present',
  },
  {
    id: 'att-9',
    employeeId: 'emp-3',
    employeeName: 'Priya Patel',
    employeeAvatar: initialEmployees[2].avatarUrl,
    date: '2025-10-21',
    checkIn: '09:30 AM',
    checkOut: '05:30 PM',
    workHours: 7.0,
    breakMinutes: 60,
    extraHours: 0.0,
    status: 'present',
  },
  {
    id: 'att-10',
    employeeId: 'emp-4',
    employeeName: 'Rahul Verma',
    employeeAvatar: initialEmployees[3].avatarUrl,
    date: '2025-10-21',
    checkIn: '09:10 AM',
    checkOut: '06:10 PM',
    workHours: 8.0,
    breakMinutes: 60,
    extraHours: 0.0,
    status: 'present',
  },
  {
    id: 'att-11',
    employeeId: 'emp-5',
    employeeName: 'Sneha Kulkarni',
    employeeAvatar: initialEmployees[4].avatarUrl,
    date: '2025-10-21',
    checkIn: '09:20 AM',
    checkOut: '07:20 PM',
    workHours: 9.0,
    breakMinutes: 60,
    extraHours: 1.0,
    status: 'present',
  },
  {
    id: 'att-12',
    employeeId: 'emp-6',
    employeeName: 'Vikram Malhotra',
    employeeAvatar: initialEmployees[5].avatarUrl,
    date: '2025-10-21',
    checkIn: '09:15 AM',
    checkOut: '06:15 PM',
    workHours: 8.0,
    breakMinutes: 60,
    extraHours: 0.0,
    status: 'present',
  },

  // 20 October 2025
  {
    id: 'att-13',
    employeeId: 'emp-2',
    employeeName: 'John Doe',
    employeeAvatar: initialEmployees[1].avatarUrl,
    date: '2025-10-20',
    checkIn: '09:25 AM',
    checkOut: '06:30 PM',
    workHours: 8.08,
    breakMinutes: 60,
    extraHours: 0.08,
    status: 'present',
  },
  {
    id: 'att-14',
    employeeId: 'emp-1',
    employeeName: 'Amit Sharma',
    employeeAvatar: initialEmployees[0].avatarUrl,
    date: '2025-10-20',
    checkIn: '09:00 AM',
    checkOut: '06:15 PM',
    workHours: 8.25,
    breakMinutes: 60,
    extraHours: 0.25,
    status: 'present',
  },
  {
    id: 'att-15',
    employeeId: 'emp-3',
    employeeName: 'Priya Patel',
    employeeAvatar: initialEmployees[2].avatarUrl,
    date: '2025-10-20',
    checkIn: '09:30 AM',
    checkOut: '06:30 PM',
    workHours: 8.0,
    breakMinutes: 60,
    extraHours: 0.0,
    status: 'present',
  },
];

export const initialTimeOffRequests: TimeOffRequest[] = [
  {
    id: 'to-1',
    employeeId: 'emp-3',
    employeeName: 'Priya Patel',
    employeeAvatar: initialEmployees[2].avatarUrl,
    department: 'Product Design',
    timeOffType: 'Paid Time Off',
    startDate: '2025-10-22',
    endDate: '2025-10-24',
    days: 3.0,
    reason: 'Attending Figma Config Regional & family festival trip',
    status: 'approved',
    appliedDate: '2025-10-15',
    reviewedBy: 'Amit Sharma',
    reviewedDate: '2025-10-16',
    reviewComment: 'Approved. Design deliverables handed over.',
  },
  {
    id: 'to-2',
    employeeId: 'emp-2',
    employeeName: 'John Doe',
    employeeAvatar: initialEmployees[1].avatarUrl,
    department: 'Frontend Engineering',
    timeOffType: 'Paid Time Off',
    startDate: '2025-11-12',
    endDate: '2025-11-14',
    days: 3.0,
    reason: 'Diwali break extended with family in hometown',
    status: 'pending',
    appliedDate: '2025-10-20',
  },
  {
    id: 'to-3',
    employeeId: 'emp-4',
    employeeName: 'Rahul Verma',
    employeeAvatar: initialEmployees[3].avatarUrl,
    department: 'Platform & Cloud Infrastructure',
    timeOffType: 'Sick Leave',
    startDate: '2025-10-10',
    endDate: '2025-10-11',
    days: 2.0,
    reason: 'Viral fever and prescribed medical bed rest',
    attachmentName: 'medical_certificate_apollo.pdf',
    attachmentDataUrl: '#sample-certificate',
    status: 'approved',
    appliedDate: '2025-10-09',
    reviewedBy: 'Amit Sharma',
    reviewedDate: '2025-10-10',
  },
  {
    id: 'to-4',
    employeeId: 'emp-5',
    employeeName: 'Sneha Kulkarni',
    employeeAvatar: initialEmployees[4].avatarUrl,
    department: 'Product Management',
    timeOffType: 'Sick Leave',
    startDate: '2025-11-05',
    endDate: '2025-11-06',
    days: 2.0,
    reason: 'Dental surgery and post-op recovery',
    attachmentName: 'dentist_fit_note_dr_mehta.pdf',
    attachmentDataUrl: '#sample-certificate',
    status: 'pending',
    appliedDate: '2025-10-21',
  },
  {
    id: 'to-5',
    employeeId: 'emp-6',
    employeeName: 'Vikram Malhotra',
    employeeAvatar: initialEmployees[5].avatarUrl,
    department: 'Quality Assurance',
    timeOffType: 'Unpaid Leave',
    startDate: '2025-09-18',
    endDate: '2025-09-19',
    days: 2.0,
    reason: 'Personal urgent relocation matters',
    status: 'rejected',
    appliedDate: '2025-09-15',
    reviewedBy: 'Amit Sharma',
    reviewedDate: '2025-09-16',
    reviewComment: 'Sprint regression testing week; please reschedule or use PTO balance.',
  },
];

export const defaultAllocations: Record<string, TimeOffAllocation> = {
  'emp-1': {
    paidTimeOffTotal: 24,
    paidTimeOffUsed: 2,
    sickLeaveTotal: 7,
    sickLeaveUsed: 0,
    unpaidLeaveUsed: 0,
  },
  'emp-2': {
    paidTimeOffTotal: 24,
    paidTimeOffUsed: 4,
    sickLeaveTotal: 7,
    sickLeaveUsed: 1,
    unpaidLeaveUsed: 0,
  },
  'emp-3': {
    paidTimeOffTotal: 24,
    paidTimeOffUsed: 6,
    sickLeaveTotal: 7,
    sickLeaveUsed: 0,
    unpaidLeaveUsed: 0,
  },
  'emp-4': {
    paidTimeOffTotal: 24,
    paidTimeOffUsed: 3,
    sickLeaveTotal: 7,
    sickLeaveUsed: 2,
    unpaidLeaveUsed: 0,
  },
  'emp-5': {
    paidTimeOffTotal: 24,
    paidTimeOffUsed: 5,
    sickLeaveTotal: 7,
    sickLeaveUsed: 0,
    unpaidLeaveUsed: 0,
  },
  'emp-6': {
    paidTimeOffTotal: 24,
    paidTimeOffUsed: 1,
    sickLeaveTotal: 7,
    sickLeaveUsed: 0,
    unpaidLeaveUsed: 0,
  },
};
